databases:
  - name: project_tracker_db
    databaseName: project_tracker
    user: project_tracker
    plan: free

services:
  - type: web
    name: project_tracker
    runtime: ruby
    plan: free
    buildCommand: './bin/render-build.sh'
    startCommand: 'bundle exec puma -C config/puma.rb'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: project_tracker_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
