databases:
  - name: iterate_db
    databaseName: iterate_production
    user: iterate
    plan: free
    region: oregon

services:
  - type: web
    name: iterate
    runtime: ruby
    plan: free
    region: oregon
    buildCommand: './bin/render-build.sh'
    startCommand: 'bin/rails server -b 0.0.0.0 -p $PORT -e production'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: iterate_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true
    autoDeploy: true
